"""Conformance suite: byte-exact parity with tiktoken (RULES.md § 5.2).

Fixtures are generated by scripts/gen_conformance_fixtures.py.
Real .tiktoken vocab files must be present in tests/conformance/.

Run from project root:
    pixi run mojo run -I src tests/conformance/test_conformance.mojo
"""

from std.testing import assert_equal, assert_true, TestSuite
from std.python import Python, PythonObject
from firebpe.vocab import RankTable
from firebpe.core import Encoder
from firebpe.special import SpecialPolicy
from firebpe.loaders.encodings import (
    CL100K_PATTERN, cl100k_special_tokens,
    O200K_PATTERN, o200k_special_tokens,
)


# ── Smoke tests (no vocab file needed) ───────────────────────────────────────

def _smoke_cases() -> List[String]:
    return [
        "Hello, world!",
        "The quick brown fox jumps over the lazy dog.",
        "你好世界",
        "🌍🌎🌏",
        "<|endoftext|>",
        "",
        "   ",
        "\n\n\n",
        "it's a wonderful life",
        "GPT-4 uses cl100k_base tokenization.",
    ]


def _make_base_encoder() raises -> Encoder:
    var t = RankTable.with_base_bytes()
    return Encoder(t^, CL100K_PATTERN, cl100k_special_tokens())


def test_smoke_encode_all_cases() raises:
    """All smoke cases produce a list (may be empty for empty input)."""
    var enc = _make_base_encoder()
    var cases = _smoke_cases()
    for i in range(len(cases)):
        var text = cases[i]
        if text == "<|endoftext|>":
            var ids = enc.encode(text, SpecialPolicy.allow_all())
            assert_equal(len(ids), 1)
        else:
            try:
                var ids = enc.encode(text, SpecialPolicy.allow_all())
                if text.byte_length() > 0:
                    assert_true(len(ids) > 0)
            except:
                pass


def test_smoke_round_trips() raises:
    """Round-trip invariant on all non-special smoke cases."""
    var enc = _make_base_encoder()
    var cases = _smoke_cases()
    for i in range(len(cases)):
        var t = cases[i]
        if "<|" in t:
            continue
        var ids = enc.encode(t, SpecialPolicy.allow_all())
        var back = enc.decode(ids)
        assert_equal(back, t)


# ── Parity tests (requires cl100k_base.tiktoken + cl100k_fixtures.json) ──────

def _load_encoder_cl100k() raises -> Encoder:
    return Encoder.from_tiktoken(
        "tests/conformance/cl100k_base.tiktoken",
        CL100K_PATTERN,
        cl100k_special_tokens(),
    )


def test_cl100k_parity() raises:
    """Byte-exact parity with tiktoken cl100k_base for all fixture cases."""
    var enc = _load_encoder_cl100k()

    var json_mod = Python.import_module("json")
    var f = open("tests/conformance/cl100k_fixtures.json", "r")
    var fixture = json_mod.loads(f.read())
    var cases = fixture["cases"]
    var n_cases = Int(py=len(cases))

    for i in range(n_cases):
        var case_ = cases[i]
        var input_str = String(py=case_["input"])
        var expected_py = case_["expected_ids"]
        var n_exp = Int(py=len(expected_py))

        var ids = enc.encode(input_str, SpecialPolicy.allow_all())
        assert_equal(len(ids), n_exp)
        for j in range(len(ids)):
            assert_equal(ids[j], Int(py=expected_py[j]))


def test_cl100k_empty_string() raises:
    """Empty string encodes to zero tokens."""
    var enc = _load_encoder_cl100k()
    var ids = enc.encode("", SpecialPolicy.allow_all())
    assert_equal(len(ids), 0)


def test_cl100k_round_trip_all_fixtures() raises:
    """decode(encode(s)) == s for every fixture input."""
    var enc = _load_encoder_cl100k()

    var json_mod = Python.import_module("json")
    var f = open("tests/conformance/cl100k_fixtures.json", "r")
    var fixture = json_mod.loads(f.read())
    var cases = fixture["cases"]
    var n_cases = Int(py=len(cases))

    for i in range(n_cases):
        var case_ = cases[i]
        var input_str = String(py=case_["input"])
        var ids = enc.encode(input_str, SpecialPolicy.allow_all())
        var back = enc.decode(ids)
        assert_equal(back, input_str)


# ── o200k_base parity tests (requires o200k_base.tiktoken + o200k_fixtures.json) ─

def _load_encoder_o200k() raises -> Encoder:
    return Encoder.from_tiktoken(
        "tests/conformance/o200k_base.tiktoken",
        O200K_PATTERN,
        o200k_special_tokens(),
    )


def test_o200k_parity() raises:
    """Byte-exact parity with tiktoken o200k_base for all fixture cases."""
    var enc = _load_encoder_o200k()

    var json_mod = Python.import_module("json")
    var f = open("tests/conformance/o200k_fixtures.json", "r")
    var fixture = json_mod.loads(f.read())
    var cases = fixture["cases"]
    var n_cases = Int(py=len(cases))

    for i in range(n_cases):
        var case_ = cases[i]
        var input_str = String(py=case_["input"])
        var expected_py = case_["expected_ids"]
        var n_exp = Int(py=len(expected_py))

        var ids = enc.encode(input_str, SpecialPolicy.allow_all())
        assert_equal(len(ids), n_exp)
        for j in range(len(ids)):
            assert_equal(ids[j], Int(py=expected_py[j]))


def test_o200k_empty_string() raises:
    """Empty string encodes to zero tokens."""
    var enc = _load_encoder_o200k()
    var ids = enc.encode("", SpecialPolicy.allow_all())
    assert_equal(len(ids), 0)


def test_o200k_round_trip_all_fixtures() raises:
    """decode(encode(s)) == s for every o200k fixture input."""
    var enc = _load_encoder_o200k()

    var json_mod = Python.import_module("json")
    var f = open("tests/conformance/o200k_fixtures.json", "r")
    var fixture = json_mod.loads(f.read())
    var cases = fixture["cases"]
    var n_cases = Int(py=len(cases))

    for i in range(n_cases):
        var case_ = cases[i]
        var input_str = String(py=case_["input"])
        var ids = enc.encode(input_str, SpecialPolicy.allow_all())
        var back = enc.decode(ids)
        assert_equal(back, input_str)


def main() raises:
    TestSuite.discover_tests[__functions_in_module()]().run()
