"""Tests for the HuggingFace tokenizer.json loader (SPEC § 7.2).

Uses a synthetic fixture at tests/fixtures/test_tokenizer.json generated by
the Python snippet in scripts/gen_hf_test_fixture.py. The fixture has 256
base-byte tokens + 4 merged tokens (He=256, Hel=257, Hell=258, Hello=259)
and one special token (<|endoftest|>=260).
"""

from std.testing import assert_equal, assert_true, assert_raises, TestSuite
from firebpe.core import Encoder
from firebpe.loaders.hf_json import load_hf_json, load_hf_json_full
from firebpe.loaders.byte_unicode import hf_token_str_to_bytes
from firebpe.special import SpecialPolicy


comptime FIXTURE_PATH = "tests/fixtures/test_tokenizer.json"


# ── hf_token_str_to_bytes unit tests ────────────────────────────────────────


def test_hf_token_str_to_bytes_ascii_letter() raises:
    """ASCII printable bytes map to themselves."""
    var b = hf_token_str_to_bytes("A")
    assert_equal(len(b), 1)
    assert_equal(b[0], UInt8(65))  # 'A' = 65


def test_hf_token_str_to_bytes_space() raises:
    """Space (0x20) maps to Ġ (U+0120) in GPT-2 encoding."""
    var b = hf_token_str_to_bytes("Ġ")
    assert_equal(len(b), 1)
    assert_equal(b[0], UInt8(0x20))


def test_hf_token_str_to_bytes_multibyte_token() raises:
    """Multi-char token correctly decodes to byte sequence."""
    # 'He' → bytes [72, 101] (H=72, e=101, both printable ASCII → map to themselves)
    var b = hf_token_str_to_bytes("He")
    assert_equal(len(b), 2)
    assert_equal(b[0], UInt8(72))
    assert_equal(b[1], UInt8(101))


def test_hf_token_str_to_bytes_control_byte() raises:
    """Control byte 0x00 maps to the correct GPT-2 char and back."""
    # Byte 0 maps to chr(256+last_offset) — just check it round-trips
    from firebpe.loaders.byte_unicode import byte_to_char_table
    var btc = byte_to_char_table()
    var cp = btc[0]
    # Build a 2-byte UTF-8 sequence for a codepoint in range [0x100, 0x1FF]
    var utf8_b0 = UInt8(cp >> 6 | 0xC0)
    var utf8_b1 = UInt8(cp & 0x3F | 0x80)
    var raw: List[UInt8] = [utf8_b0, utf8_b1]
    var s = String(StringSlice(unsafe_from_utf8=Span[UInt8](raw)))
    var decoded = hf_token_str_to_bytes(s)
    assert_equal(len(decoded), 1)
    assert_equal(decoded[0], UInt8(0))


# ── load_hf_json / load_hf_json_full integration tests ──────────────────────


def test_load_hf_json_table_only() raises:
    """load_hf_json returns a RankTable with 260 tokens (256 base + 4 merged)."""
    var table = load_hf_json(FIXTURE_PATH)
    assert_equal(table.n_vocab(), 260)


def test_load_hf_json_full_byte_ranks() raises:
    """Base byte tokens have correct IDs (0-255)."""
    var specials = Dict[String, Int]()
    var table = load_hf_json_full(FIXTURE_PATH, specials)
    var h_bytes: List[UInt8] = [UInt8(72)]
    assert_equal(table.rank_of(Span[UInt8](h_bytes)), UInt32(72))
    var sp_bytes: List[UInt8] = [UInt8(0x20)]
    assert_equal(table.rank_of(Span[UInt8](sp_bytes)), UInt32(0x20))


def test_load_hf_json_full_merged_token() raises:
    """Merged token 'Hello' (bytes 72,101,108,108,111) has ID 259."""
    var specials = Dict[String, Int]()
    var table = load_hf_json_full(FIXTURE_PATH, specials)
    var hello: List[UInt8] = [UInt8(72), UInt8(101), UInt8(108), UInt8(108), UInt8(111)]
    assert_equal(table.rank_of(Span[UInt8](hello)), UInt32(259))


def test_load_hf_json_full_special_tokens() raises:
    """Special token <|endoftest|> (id=260) is collected correctly."""
    var specials = Dict[String, Int]()
    var _ = load_hf_json_full(FIXTURE_PATH, specials)
    assert_true("<|endoftest|>" in specials)
    assert_equal(specials["<|endoftest|>"], 260)


def test_load_hf_json_unsupported_model_type() raises:
    """Non-BPE model type raises."""
    var path = "/tmp/firebpe_hf_bad_model.json"
    with open(path, "w") as f:
        f.write('{"model": {"type": "WordPiece", "vocab": {}}}')
    with assert_raises():
        var _ = load_hf_json(path)


def test_load_hf_json_missing_model_raises() raises:
    """Missing model field raises."""
    var path = "/tmp/firebpe_hf_no_model.json"
    with open(path, "w") as f:
        f.write('{"pre_tokenizer": {"type": "ByteLevel"}}')
    with assert_raises():
        var _ = load_hf_json(path)


def test_encoder_from_hf_json_round_trip() raises:
    """Encoder loaded from HF JSON round-trips ASCII text."""
    var enc = Encoder.from_hf_json(FIXTURE_PATH)
    var text = "Hello"
    var ids = enc.encode(text, SpecialPolicy.allow_none())
    var back = enc.decode(ids)
    assert_equal(back, text)


def test_encoder_from_hf_json_hello_is_one_token() raises:
    """'Hello' encodes to a single token (id=259) via the fixture merges."""
    var enc = Encoder.from_hf_json(FIXTURE_PATH)
    var ids = enc.encode("Hello", SpecialPolicy.allow_none())
    assert_equal(len(ids), 1)
    assert_equal(ids[0], 259)


def test_encoder_from_hf_json_n_vocab() raises:
    """Encoder reports correct vocab size including special token."""
    var enc = Encoder.from_hf_json(FIXTURE_PATH)
    assert_equal(enc.n_vocab(), 261)  # 260 mergeable + 1 special


comptime ANTHROPIC_TOKENIZER = "/mnt/c/Users/nikhi/AppData/Local/Programs/Python/Python313/Lib/site-packages/anthropic/tokenizer.json"


def test_real_anthropic_tokenizer_loads() raises:
    """Real Anthropic tokenizer.json loads without errors."""
    var enc = Encoder.from_hf_json(ANTHROPIC_TOKENIZER)
    # Anthropic BPE tokenizer: sizeable vocabulary
    assert_true(enc.n_vocab() > 50000)


def test_real_anthropic_tokenizer_round_trip() raises:
    """Real Anthropic tokenizer.json: ASCII text round-trips."""
    var enc = Encoder.from_hf_json(ANTHROPIC_TOKENIZER)
    var text = "Hello, World!"
    var ids = enc.encode(text, SpecialPolicy.allow_all())
    var back = enc.decode(ids)
    assert_equal(back, text)


def main() raises:
    TestSuite.discover_tests[__functions_in_module()]().run()
